server:
  port: 8090

  compression:
    enabled: true
    mime-types: application/json, application/xml, text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/x-javascript, audio/mpeg
    min-response-size: 2048  #2KB
    excluded-user-agents: MSIE 6.0,UCBrowser

spring:
  application:
    name: musicstore

  #  cache:
#    type: redis
#    redis:
#      cache-null-values: true

  config:
    import: classpath:custom.yml

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/music_store}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB